---
name: PPIx-Shorthand
version: 1.001000
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Translation of short names to L<PPI::Element> classes.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  Readonly: 0
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
build_requires:
  English: 0
  Test::More: 0
dynamic_config: 0
provides:
  PPIx::Shorthand:
    file: lib/PPIx/Shorthand.pm
    version: 1.001000
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
